"""Tests for classify.py — Vocabulary loading, the two-tier Matcher, semantics.

The real android.yaml/ios.yaml are generated by the harvester in parallel, so
every test here runs against a small hand-written vocabulary fixture written to
tmp_path (INTERFACES.md schema). The real semantics.yaml IS loaded in one test
(it already exists and is hand-curated).
"""
from __future__ import annotations

import logging
import time
from pathlib import Path

import pytest

from fixtures import fixture, read
import yaml

import loganalyzer
from loganalyzer.classify import (
    Matcher,
    Vocabulary,
    _entry_from_yaml,
    _literal_fragments,
    _ver_tuple,
    _in_range,
)
from loganalyzer.model import ANDROID, IOS
from loganalyzer.records import assemble

REAL_VOCAB_DIR = Path(loganalyzer.__file__).parent / "vocabulary"

# ── Hand-written vocabulary fixture (INTERFACES.md schema) ───────────────────

ANDROID_YAML = {
    "meta": {"platform": "android", "harvested_refs": {"4.5.0": "deadbeef"}},
    "entries": [
        {
            "id": "TSGeofenceManager.setLocation#1",
            "class": "TSGeofenceManager",
            "method": "setLocation",
            "source": ["geofence/TSGeofenceManager.java:1521"],
            "level": "DEBUG",
            "icon": "🔵",
            "patterns": [r"Location is within stationary radius of ([\d.]+) meters"],
            "anchor": "Location is within stationary radius of ",
            "valid_from": "4.0.0",
            "valid_to": None,
            "flags": [],
        },
        {
            "id": "TSConfig.hydrateTime#1",
            "class": "TSConfig",
            "method": "hydrateTime",
            "source": ["config/TSConfig.java:88"],
            "level": "INFO",
            "icon": "",
            "patterns": [r"\[TSConfig hydrateTime\] (\d+)ms"],
            "anchor": "[TSConfig hydrateTime] ",
        },
        # duplicate-literal pair: level+icon tie-break must separate them
        {
            "id": "HttpService.flush#1",
            "class": "HttpService",
            "method": "flush",
            "source": ["http/HttpService.java:300"],
            "level": "DEBUG",
            "icon": "🔵",
            "patterns": [r"Flush requested: (\d+) records"],
        },
        {
            "id": "ScheduleService.flush#1",
            "class": "ScheduleService",
            "method": "flush",
            "source": ["scheduler/ScheduleService.java:90"],
            "level": "WARN",
            "icon": "⚠",
            "patterns": [r"Flush requested: (\d+) records"],
        },
        # byte-identical unsplittable pair -> honest ambiguous tie
        {
            "id": "EvalA.run#1",
            "class": "EvalA",
            "method": "run",
            "source": ["eval/EvalA.java:10"],
            "level": "DEBUG",
            "icon": "🔵",
            "patterns": [r"Evaluation buffer elapsed"],
        },
        {
            "id": "EvalB.run#1",
            "class": "EvalB",
            "method": "run",
            "source": ["eval/EvalB.java:20"],
            "level": "DEBUG",
            "icon": "🔵",
            "patterns": [r"Evaluation buffer elapsed"],
        },
        # builder catch-all: fires only when no literal hit, scoped by class/level/icon
        {
            "id": "TSProviderManager.emit#1",
            "class": "TSProviderManager",
            "method": "emit",
            "source": ["provider/TSProviderManager.java:55"],
            "level": "DEBUG",
            "icon": "🔵",
            "patterns": [r"(?s).*"],
            "anchor": "",
            "flags": ["builder-catchall"],
        },
        # emoji-sequence anchor for a literal-poor site
        {
            "id": "GeofenceAnnouncer.announce#1",
            "class": "GeofenceAnnouncer",
            "method": "announce",
            "source": ["geofence/GeofenceAnnouncer.java:42"],
            "level": "DEBUG",
            "icon": "📢",
            "patterns": [r"📢 (\w+)"],
        },
        # version-ranged legacy site
        {
            "id": "OldSite.emit#1",
            "class": "OldSite",
            "method": "emit",
            "source": ["legacy/OldSite.java:7"],
            "level": "INFO",
            "icon": "🎾",
            "patterns": [r"Legacy tennis-ball ON marker engaged"],
            "valid_from": "4.0.0",
            "valid_to": "4.5.0",
            "flags": ["legacy"],
        },
    ],
}

IOS_YAML = {
    "meta": {"platform": "ios", "harvested_refs": {"4.4.2": "cafebabe"}},
    "entries": [
        {
            "id": "TSMotionDetector.activitySourceDidUpdate#1",
            "class": "TSMotionDetector",
            "method": "activitySourceDidUpdate:",
            "source": ["TSMotionDetector.m:210"],
            "level": None,
            "icon": "🔵",
            "patterns": [r"MotionActivity Rx <CMMotionActivity"],
            "anchor": "MotionActivity Rx <CMMotionActivity",
        },
        {
            # deliberately fewer selector parts than the record emits:
            # the class-alone fallback bucket must still find it
            "id": "TSTimerService.start#1",
            "class": "TSTimerService",
            "method": "start:",
            "source": ["TSTimerService.m:44"],
            "icon": "🟢",
            "patterns": [r"Starting timer: ([\d.]+)s repeating: (\d)"],
        },
        {
            "id": "TSDataStore.persist#1",
            "class": "TSDataStore",
            "method": "persist:",
            "source": ["TSDataStore.m:118"],
            "icon": "✅",
            "patterns": [r"💾 INSERT: ([A-F0-9-]+)"],
            "semantic": "persist.insert",
            "family": "domain",
        },
        {
            "id": "TSLocationManager.log#1",
            "class": "TSLocationManager",
            "method": "log:message:",
            "source": ["TSLocationManager.m:999"],
            "patterns": [],
            "flags": ["passthrough"],
        },
        {
            "id": "OldIos.emit#1",
            "class": "OldIos",
            "method": "emit:",
            "source": ["OldIos.m:31"],
            "icon": "🔵",
            "patterns": [r"Old-style emission marker"],
            "valid_to": "4.4.3",
        },
    ],
}

IOS_BUILDS_YAML = {"388": "4.4.2", "401": "4.4.4"}

SEMANTICS_YAML = {
    "icon_semantics": {
        "android": [
            {"icon": "⚠", "semantic": "warn", "family": "severity"},
            {"icon": "‼", "semantic": "error", "family": "severity"},
            {"icon": "🔵", "semantic": "notice", "family": "severity"},
            {"icon": "✅", "semantic": "ok", "family": "state"},
            {"icon": "🟢", "semantic": "on", "family": "state", "valid_from": "4.5.1"},
            {"icon": "🎾", "semantic": "on", "family": "state", "valid_to": "4.5.0"},
            {"icon": "🚫", "semantic": "cancel", "family": "state", "valid_from": "4.5.1"},
            {"icon": "❌", "semantic": "cancel", "family": "state", "valid_to": "4.5.0"},
            {"icon": "📢", "semantic": "geofence_announce", "family": "domain"},
        ],
        "ios": [
            {"icon": "⚠", "semantic": "warn", "family": "severity"},
            {"icon": "‼", "semantic": "error", "family": "severity", "valid_from": "4.4.4"},
            {"icon": "❌", "semantic": "error", "family": "severity", "valid_to": "4.4.3"},
            {"icon": "🔵", "semantic": "notice", "family": "severity"},
            {"icon": "🟢", "semantic": "on", "family": "state"},
            {"icon": "✅", "semantic": "ok", "family": "state"},
            {"icon": "📌🔒", "semantic": "auth", "family": "domain"},
        ],
    },
    "body_emoji_hints": {
        "☯": "app_lifecycle",
        "💀": "headless",
        "💾": "persistence",
    },
    "categories": [
        {"match_class": "TSAppState|LifecycleManager", "category": "lifecycle"},
        {"match_body_hint": "app_lifecycle", "category": "lifecycle"},
        {"match_body_hint": "headless", "category": "lifecycle"},
        {"match_class": "TSGeofence.*|GeofenceAnnouncer", "category": "geofence"},
        {"match_class": ".*Http.*", "category": "http"},
        {"match_class": "TSMotionDetector|.*MotionActivity.*", "category": "motion"},
        {"match_class": "TSDataStore|SQLiteLocationDAO", "category": "persistence"},
        {"match_class": "TSTimerService|TSHeartbeatService", "category": "power"},
        {"match_class": "TSConfig|TSLog|LoggerFacade.*", "category": "system"},
    ],
}


@pytest.fixture(scope="module")
def vocab_dir(tmp_path_factory) -> Path:
    d = tmp_path_factory.mktemp("vocab")
    (d / "android.yaml").write_text(yaml.safe_dump(ANDROID_YAML, allow_unicode=True), encoding="utf-8")
    (d / "ios.yaml").write_text(yaml.safe_dump(IOS_YAML, allow_unicode=True), encoding="utf-8")
    (d / "ios-builds.yaml").write_text(yaml.safe_dump(IOS_BUILDS_YAML, allow_unicode=True), encoding="utf-8")
    (d / "semantics.yaml").write_text(yaml.safe_dump(SEMANTICS_YAML, allow_unicode=True), encoding="utf-8")
    return d


@pytest.fixture(scope="module")
def matcher(vocab_dir) -> Matcher:
    return Matcher(Vocabulary.load(vocab_dir))


def android_rec(text: str):
    recs = assemble(ANDROID, text, base_year=2026)
    assert len(recs) == 1, f"expected one record, got {len(recs)}"
    return recs[0]


def ios_rec(text: str):
    recs = assemble(IOS, text, base_year=2026)
    assert len(recs) == 1, f"expected one record, got {len(recs)}"
    return recs[0]


# ── Vocabulary loading ───────────────────────────────────────────────────────

class TestVocabularyLoad:
    def test_missing_files_warn_but_load(self, tmp_path, caplog):
        with caplog.at_level(logging.WARNING, logger="loganalyzer.classify"):
            vocab = Vocabulary.load(tmp_path)
        assert vocab.entries == []
        assert vocab.build_map == {}
        missing = " ".join(caplog.messages)
        for name in ("android.yaml", "ios.yaml", "ios-builds.yaml", "semantics.yaml"):
            assert name in missing
        # classifier still constructs and runs against an empty vocabulary
        m = Matcher(vocab)
        rec = android_rec("07-03 23:36:43.936 DEBUG [Foo bar] hello world")
        klass = m.classify(rec, None)
        assert klass.status == "unknown"
        assert rec.klass is klass

    def test_fixture_vocab_parses(self, vocab_dir):
        vocab = Vocabulary.load(vocab_dir)
        platforms = {e.platform for e in vocab.entries}
        assert platforms == {ANDROID, IOS}
        assert len(vocab.entries) == len(ANDROID_YAML["entries"]) + len(IOS_YAML["entries"])
        # build map keys/values coerced to str
        assert vocab.build_map["388"] == "4.4.2"
        assert all(isinstance(k, str) and isinstance(v, str) for k, v in vocab.build_map.items())

    def test_real_semantics_layer_loads(self):
        # android.yaml/ios.yaml may or may not exist yet (harvested in
        # parallel) — semantics.yaml is committed and must load.
        vocab = Vocabulary.load(REAL_VOCAB_DIR)
        assert vocab.semantics.get("icon_semantics")
        assert vocab.semantics.get("categories")
        m = Matcher(vocab)
        rec = android_rec(
            "07-03 23:36:44.211 DEBUG [TSGeofenceManager evaluate] evaluate IGNORED"
        )
        klass = m.classify(rec, "4.2.1")
        assert klass.category == "geofence"


# ── Version helpers ──────────────────────────────────────────────────────────

class TestVersioning:
    def test_ver_tuple(self):
        assert _ver_tuple("4.2.1") == (4, 2, 1)
        assert _ver_tuple("4.2.1 (4063)") == (4, 2, 1)
        assert _ver_tuple(None) is None
        assert _ver_tuple("garbage") is None

    def test_in_range_inclusive_and_padded(self):
        assert _in_range((4, 5, 0), _ver_tuple("4.0.0"), _ver_tuple("4.5.0"))
        assert not _in_range((4, 5, 1), _ver_tuple("4.0.0"), _ver_tuple("4.5.0"))
        assert _in_range((4, 5), _ver_tuple("4.5.0"), None)      # (4,5) == (4,5,0)
        assert _in_range(None, _ver_tuple("4.0.0"), _ver_tuple("4.1.0"))  # unknown = no filter


# ── Literal fragment extraction ──────────────────────────────────────────────

class TestLiteralFragments:
    def test_plain_fragments_with_groups(self):
        frags = dict(_literal_fragments(r"Starting timer: ([\d.]+)s repeating: (\d)"))
        assert frags["Starting timer: "] is True
        assert frags["s repeating: "] is True

    def test_escaped_metachars_are_literal(self):
        frags = dict(_literal_fragments(r"isMoving: (.*?) \| stateChanged: "))
        assert frags["isMoving: "] is True
        assert frags[" | stateChanged: "] is True

    def test_alternation_marks_unsafe(self):
        frags = dict(_literal_fragments(r"prefix (ENTER|EXIT) suffix"))
        assert frags["prefix "] is True
        assert frags[" suffix"] is True
        assert frags["ENTER"] is False
        assert frags["EXIT"] is False

    def test_optional_group_and_quantified_char_unsafe(self):
        frags = dict(_literal_fragments(r"head (tail)? end{2} zz"))
        assert frags["head "] is True
        assert frags["tail"] is False       # (…)? is optional
        assert frags[" en"] is True         # the quantified 'd' is dropped
        assert frags[" zz"] is True


# ── Android matching ─────────────────────────────────────────────────────────

class TestAndroidMatching:
    def test_exact_match_real_tag(self, matcher):
        rec = android_rec(
            "07-03 23:36:43.936 DEBUG [TSGeofenceManager setLocation] \n"
            "  🔵  Location is within stationary radius of 25.0 meters"
        )
        klass = matcher.classify(rec, "4.5.0")
        assert klass.status == "matched"
        assert klass.confidence == "exact"
        assert klass.sites == ["geofence/TSGeofenceManager.java:1521"]
        assert klass.category == "geofence"
        assert klass.semantic == "notice"       # from 🔵 icon semantics
        assert rec.klass is klass

    def test_helper_tag_joins_by_literal(self, matcher):
        # every line of many captures is tagged [LoggerFacade$Entry log]:
        # tag weight must drop to 0 and the literal must carry the join
        rec = android_rec(
            "07-03 23:36:44.000 DEBUG [LoggerFacade$Entry log] \n"
            "  🔵  Location is within stationary radius of 30.5 meters"
        )
        klass = matcher.classify(rec, None)
        assert klass.status == "matched"
        assert klass.sites == ["geofence/TSGeofenceManager.java:1521"]
        # category comes from the ENTRY's class, not the helper frame
        assert klass.category == "geofence"

    def test_pseudo_tag_retag_still_matches(self, matcher):
        rec = android_rec(
            "07-03 23:36:43.936 INFO [LoggerFacade$Entry log] ⏱️ [TSConfig hydrateTime] 123ms"
        )
        assert rec.tag_class == "TSConfig"      # records.py re-tagged it
        klass = matcher.classify(rec, None)
        assert klass.status == "matched"
        assert klass.sites == ["config/TSConfig.java:88"]
        assert klass.category == "system"

    def test_level_icon_tiebreak_on_duplicate_literals(self, matcher):
        rec = android_rec(
            "07-03 23:36:45.000 WARN [LoggerFacade$Entry log] \n"
            "  ⚠️  Flush requested: 5 records"
        )
        klass = matcher.classify(rec, None)
        assert klass.status == "matched"
        assert klass.confidence == "exact"
        assert klass.sites == ["scheduler/ScheduleService.java:90"]   # WARN+⚠ agree

    def test_unsplittable_duplicate_pair_is_honest_ambiguous(self, matcher):
        rec = android_rec(
            "07-03 23:36:45.500 DEBUG [LoggerFacade$Entry log] \n"
            "  🔵  Evaluation buffer elapsed"
        )
        klass = matcher.classify(rec, None)
        assert klass.status == "matched"
        assert klass.confidence == "ambiguous"
        assert set(klass.sites) == {"eval/EvalA.java:10", "eval/EvalB.java:20"}

    def test_catchall_fires_only_without_literal_hit(self, matcher):
        # no literal matches -> the class-scoped builder catch-all takes it
        rec = android_rec(
            "07-03 23:36:46.000 DEBUG [TSProviderManager emit] \n"
            "  🔵  some ad-hoc builder string 999"
        )
        klass = matcher.classify(rec, None)
        assert klass.status == "matched"
        assert klass.sites == ["provider/TSProviderManager.java:55"]

        # a literal hit anywhere outranks the catch-all even on the same tag
        rec2 = android_rec(
            "07-03 23:36:46.100 DEBUG [TSProviderManager emit] \n"
            "  🔵  Location is within stationary radius of 12 meters"
        )
        klass2 = matcher.classify(rec2, None)
        assert klass2.status == "matched"
        assert klass2.sites == ["geofence/TSGeofenceManager.java:1521"]

    def test_emoji_anchor_for_literal_poor_site(self, matcher):
        rec = android_rec(
            "07-03 23:40:00.000 DEBUG [GeofenceAnnouncer announce] \n"
            "  📢 ENTER"
        )
        klass = matcher.classify(rec, None)
        assert klass.status == "matched"
        assert klass.sites == ["geofence/GeofenceAnnouncer.java:42"]
        assert klass.category == "geofence"

    def test_version_filter_excludes_retired_entry(self, matcher):
        line = (
            "07-03 23:41:00.000 INFO [OldSite emit] \n"
            "  🎾  Legacy tennis-ball ON marker engaged"
        )
        old = matcher.classify(android_rec(line), "4.2.0")
        assert old.status == "matched"
        assert old.semantic == "on"             # 🎾 was always meant as ON
        assert old.family == "state"

        new = matcher.classify(android_rec(line), "4.6.0")
        assert new.status == "unknown"          # entry retired at 4.5.0
        assert new.semantic == ""               # 🎾 icon rule retired too

        unversioned = matcher.classify(android_rec(line), None)
        assert unversioned.status == "matched"  # no version = no filter

    def test_drift_when_message_mutated(self, matcher):
        rec = android_rec(
            "07-03 23:36:47.000 DEBUG [TSGeofenceManager setLocation] \n"
            "  🔵  Location is inside stationary radius of 25.0 meters now"
        )
        klass = matcher.classify(rec, None)
        assert klass.status == "drift"
        assert klass.drift_of == "TSGeofenceManager.setLocation#1"
        assert klass.confidence == "fuzzy"
        assert klass.sites == ["geofence/TSGeofenceManager.java:1521"]

    def test_unknown_still_categorized(self, matcher):
        rec = android_rec(
            "07-03 23:36:48.000 DEBUG [TSHttpService flush] \n"
            "  🔵  Completely novel emission xyzzy"
        )
        klass = matcher.classify(rec, None)
        assert klass.status == "unknown"
        assert klass.drift_of == ""
        assert klass.category == "http"         # class rules still apply

    def test_body_hint_category(self, matcher):
        rec = android_rec(
            "07-03 23:36:49.000 DEBUG [WeirdClass foo] ☯️  onStart"
        )
        klass = matcher.classify(rec, None)
        assert klass.category == "lifecycle"    # ☯ body hint


# ── iOS matching ─────────────────────────────────────────────────────────────

class TestIosMatching:
    def test_bucket_match_with_block_invoke(self, matcher):
        rec = ios_rec(
            "2026-08-09 10:37:16.251 🔵 -[TSMotionDetector activitySourceDidUpdate:]"
            "_block_invoke MotionActivity Rx <CMMotionActivity st:0 auto:1 conf:2>\n"
        )
        assert rec.tag_method == "activitySourceDidUpdate:"   # normalized upstream
        klass = matcher.classify(rec, "4.4.2")
        assert klass.status == "matched"
        assert klass.sites == ["TSMotionDetector.m:210"]
        assert klass.category == "motion"

    def test_class_alone_fallback_when_selectors_differ(self, matcher):
        # record selector has more parts than the harvested "start:" method
        rec = ios_rec(
            "2026-08-09 10:37:16.251 🟢 -[TSTimerService "
            "startWithInterval:repeating:callback:] ⏰ [motionTriggerDelay] "
            "Starting timer: 11.00s repeating: 0\n"
        )
        klass = matcher.classify(rec, None)
        assert klass.status == "matched"
        assert klass.sites == ["TSTimerService.m:44"]
        assert klass.semantic == "on"           # 🟢 icon semantics
        assert klass.category == "power"

    def test_entry_semantic_wins_over_icon(self, matcher):
        rec = ios_rec(
            "2026-08-09 10:37:16.296 ✅ -[TSDataStore persist:] 💾 INSERT: "
            "6846FA22-260C-4634-B067-0028CF812A96 (type: 0)\n"
        )
        klass = matcher.classify(rec, None)
        assert klass.status == "matched"
        assert klass.semantic == "persist.insert"   # vocabulary entry, not ✅
        assert klass.family == "domain"
        assert klass.category == "persistence"

    def test_passthrough_never_pattern_matches_body(self, matcher):
        # the body would literal-match TSTimerService's pattern — but the
        # bridge pass-through site is app-authored, so it must short-circuit
        rec = ios_rec(
            "2026-08-09 10:38:00.000 🔵 -[TSLocationManager log:message:] "
            "Starting timer: 5.00s repeating: 1\n"
        )
        klass = matcher.classify(rec, None)
        assert klass.status == "passthrough"
        assert klass.sites == ["TSLocationManager.m:999"]

    def test_build_version_resolution(self, matcher):
        line = "2026-08-09 10:39:00.000 🔵 -[OldIos emit:] Old-style emission marker\n"
        # build 388 -> 4.4.2 <= valid_to 4.4.3 -> in range
        assert matcher.classify(ios_rec(line), "build 388").status == "matched"
        # build 401 -> 4.4.4 -> retired
        assert matcher.classify(ios_rec(line), "build 401").status == "unknown"
        # unmapped build -> no filter
        assert matcher.classify(ios_rec(line), "build 999").status == "matched"

    def test_multi_emoji_icon_semantics(self, matcher):
        rec = ios_rec(
            "2026-08-09 10:40:00.000 📌 🔒 -[UnknownAuth refresh] token refresh gate passed\n"
        )
        assert rec.icon == "📌🔒"
        klass = matcher.classify(rec, None)
        assert klass.semantic == "auth"
        assert klass.family == "domain"

    def test_tagless_record_matches_via_automaton(self, matcher):
        # banner-style record: selector lives in a ║ body row, tag fields None
        rec = ios_rec(
            "2026-08-09 10:41:00.000 \n"
            "╔═══════════════════════════════════════════════\n"
            "║ -[TSTimerService startWithInterval:repeating:callback:] "
            "Starting timer: 9.00s repeating: 1\n"
            "╚═══════════════════════════════════════════════\n"
        )
        assert rec.tag_class is None
        klass = matcher.classify(rec, None)
        assert klass.status == "matched"
        assert klass.sites == ["TSTimerService.m:44"]


# ── Real fixture logs (smoke: never raises, always classifies) ───────────────

ANDROID_FIXTURE = fixture("slc")
IOS_FIXTURE = fixture("bike")


class TestRealLogsSmoke:
    @pytest.mark.skipif(ANDROID_FIXTURE is None, reason="fixture log absent")
    def test_android_fixture(self, matcher):
        text = read(ANDROID_FIXTURE)
        records = assemble(ANDROID, text, base_year=2026)
        assert records
        for rec in records:
            klass = matcher.classify(rec, "4.2.1")
            assert klass.status in {"matched", "drift", "unknown", "passthrough"}
            assert rec.klass is klass

    @pytest.mark.skipif(IOS_FIXTURE is None, reason="fixture log absent")
    def test_ios_fixture_slice(self, matcher):
        # a slice, not the whole capture — this is a throughput smoke test
        text = read(IOS_FIXTURE)[:400_000]
        text = text.rsplit("\n\n", 1)[0]        # drop the possibly-truncated tail
        records = assemble(IOS, text, base_year=2026)
        assert len(records) > 100
        for rec in records:
            klass = matcher.classify(rec, "build 388")
            assert klass.status in {"matched", "drift", "unknown", "passthrough"}


# ── Micro-benchmark: >= 10k records/sec with a 1000-entry vocabulary ─────────

N_BENCH_ENTRIES = 1000
N_BENCH_RECORDS = 20_000


@pytest.fixture(scope="module")
def synthetic_matcher() -> Matcher:
    entries = []
    for i in range(N_BENCH_ENTRIES):
        entries.append({
            "id": f"Class{i % 50}.method{i}#1",
            "class": f"Class{i % 50}",
            "method": f"method{i}",
            "source": [f"pkg/Class{i % 50}.java:{i + 100}"],
            "level": "DEBUG",
            "icon": "🔵",
            "patterns": [rf"synthetic site {i:04d} event: code=(\d+) state=(\w+)"],
            "anchor": f"synthetic site {i:04d} event: code=",
            "valid_from": "4.0.0",
            "valid_to": None,
            "flags": [],
        })
    vocab = Vocabulary(
        entries=[_entry_from_yaml(e, ANDROID, i) for i, e in enumerate(entries)],
        semantics=SEMANTICS_YAML,
        build_map={},
    )
    return Matcher(vocab)


@pytest.fixture(scope="module")
def synthetic_records() -> list:
    lines = []
    for j in range(N_BENCH_RECORDS):
        i = j % N_BENCH_ENTRIES
        lines.append(
            f"07-03 12:00:{j % 60:02d}.{j % 1000:03d} DEBUG [Class{i % 50} method{i}] \n"
            f"  🔵  synthetic site {i:04d} event: code={j} state=ok"
        )
    records = assemble(ANDROID, "\n".join(lines), base_year=2026)
    assert len(records) == N_BENCH_RECORDS
    return records


class TestThroughput:
    def test_classifies_10k_records_per_second(self, synthetic_matcher, synthetic_records):
        t0 = time.perf_counter()
        for rec in synthetic_records:
            synthetic_matcher.classify(rec, "4.5.0")
        elapsed = time.perf_counter() - t0
        rate = len(synthetic_records) / elapsed

        matched = sum(1 for r in synthetic_records if r.klass.status == "matched")
        assert matched == len(synthetic_records)      # the benchmark measures real matching
        exact = sum(1 for r in synthetic_records if r.klass.confidence == "exact")
        assert exact == len(synthetic_records)
        assert rate >= 10_000, f"only {rate:.0f} records/sec (need >= 10k)"
